/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author USER
 */
public class Internal extends javax.swing.JInternalFrame {

    /**
     * Creates new form Internal
     */
    public Internal() {
        initComponents();
        this.setBorder((javax.swing.BorderFactory.createEmptyBorder(0,0, 0, 0)));
        BasicInternalFrameUI bi=(BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(1150, 850));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea2.setBackground(new java.awt.Color(34, 47, 65));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 13)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea2.setRows(5);
        jTextArea2.setText("                             \n                               \n\n\n                                           STAY STRONG CHAMPION...THERE IS ARAINBOW AFTER EVERY STROM.\n\n \n\n                  \n\n                                      The main purpose of education is to ignite the flames of curiosity and dreams. \n\n                                We are all naturally born students of nature. If people have a word to achieve with the name, \n                               then this achievement is the greatest. In this case, curiosity and dreams are the achievement. \n                               Sadly, in the midst of a troubled Criticism, we are seeing the death of our curiosity and dreams.\n\n\n                                 Now our soul says \"Don't be curious anymore, don't dream or I can't suffer death anymore.\"\n                                 We are late to follow the dream path.\n\n\n                               And we want the \"Athena family\" to be a part of this new path for every people of our beloved \n                               homeland Bangladesh.               \n\n\n\n\n                                                                                                 \n                                     \n\n\n\n\n\n\n                                                                      112, Green Road, Farmgate,                                            \n                                                        Eden complex, Motijheel (2nd & 5th floor) (3.88 km)\n                                                                               1205 Dhaka, \n                                                                               Bangladesh.\n                                                                            01678443300-99");
        jTextArea2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 255), 3, true));
        jScrollPane2.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 740));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
